table FinData
	lineageTag: b596fb14-c201-4627-bbe0-4b7a45ab7898

	column Type
		dataType: string
		lineageTag: b4f2ae83-1553-4b19-8909-234216ea6ad6
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Component
		dataType: string
		lineageTag: 0d1ebc93-7513-4dea-a6c1-dda2085bc2f0
		summarizeBy: none
		sourceColumn: Component

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 96966d63-1001-492f-8d0a-9f79c407d047
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 773b19f6-b062-4486-95bd-da38be9310b3
			defaultHierarchy: LocalDateTable_f95503ea-e67a-4f59-bbae-2540fd353c0c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Value
		dataType: int64
		formatString: 0
		lineageTag: e4cebc10-847e-4afc-8353-bff51c268b86
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Year = FORMAT(FinData[Date],"YYYY")
		lineageTag: 39b6cb81-365a-4e56-9eb8-d1dc486749a9
		summarizeBy: none

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Month-Year = FORMAT(FinData[Date],"MMM-YY")
		lineageTag: ae3184d0-c916-4075-b308-3266bf324dd1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FinData = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Finance-Analytics-Dashboard\Finance Dataset.xlsx"), null, true),
				    FinData_Sheet = Source{[Item="FinData",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FinData_Sheet, [PromoteAllScalars=true]),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"Type", "Component"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}, {"Value", Int64.Type}, {"Component", type text}, {"Type", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

