table 'Key Measures'
	lineageTag: 85ddf5e3-f068-4e97-8ee4-0a913bb0093c

	measure 'Total Value' = sum(FinData[Value])
		formatString: 0
		lineageTag: 5ac401c6-88a5-4550-83e3-1af9f6a2e4b9

	measure Income = CALCULATE([Total Value],FinData[Type]="Income")
		formatString: 0
		lineageTag: 2804a3cd-58d4-453c-9710-bcc890e5f7a1

	measure Savings = CALCULATE([Total Value],FinData[Type]="Savings")
		formatString: 0
		lineageTag: 655f9824-7dd7-462f-aed2-6d73fdb8b14f

	measure Expense = CALCULATE([Total Value],FinData[Type]="Expense")
		formatString: 0
		lineageTag: b40088a1-0dac-4299-96ce-d6b345b17cdc

	measure Savings% = DIVIDE([Savings],[Income])
		lineageTag: c45dc7f0-033c-43ca-bd5c-3e573d9e77e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Expense% = DIVIDE([Expense],[Income])
		lineageTag: 022c0602-dd97-48ef-80b8-352f1397cc12

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income LM' = CALCULATE([Income], DATEADD(FinData[Date],-1,MONTH))
		formatString: 0
		lineageTag: 8a59b53f-5f02-4293-b900-27ad0b94b0fe

	measure 'Income Change MoM%' = DIVIDE([Income],[Income LM])
		lineageTag: cd0439b5-955b-4d2d-86b1-2991dce69cfb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Target% = CALCULATE([Total Value],FinData[Type]="Target")
		formatString: 0%;-0%;0%
		lineageTag: 0fc42fd7-6bc2-46e7-bb1d-ffcc0593a8ab

	partition 'Key Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

